### ISSUE TITLE
module or package defining core metadata/attributes (per product?)

### ISSUE THREAD

**Issue by bbauerma** [TUW-GEO/yeoda#1]

**Comment by cnavacch** [comment]
Since this recently popped up - should we define the metadata attributes on a data cube level? So we would have a dictionary defining the metadata attributes being expected for a each specific product. This would then be passed to veranda for writing and reading the metadata to/from files.

**Comment by cnavacch** [comment]
This is now partially solved with `medali`. For all other (higher-level) things it might be worth to look into STAC.
