### ISSUE TITLE
SSM Datacube

### ISSUE THREAD

**Issue by fl0roth** [TUW-GEO/yeoda#11]
The SSM product datacube is not working. There is a typing error in the initialization of the parent class at the parameter "sres".

**Comment by cnavacch** [comment]
I have added tests and some bug fixes in https://github.com/TUW-GEO/yeoda/pull/13
which will be integrated in the new yeoda release `0.2.0`. I hope this solves this bug. 
If yes, please close this issue.

**Comment by cnavacch** [comment]
@fl0roth Any updates on this?

**Comment by fl0roth** [comment]
I haven't checked it yet but I put it on my list!

**Comment by fl0roth** [comment]
I have tested the initialization, filtering and loading of the SSM datacube within the current master branch and everything works as expected.

**Comment by cnavacch** [comment]
Thanks for checking, @fl0roth!
