### ISSUE TITLE
B01: determine the maximum limit of array size to be laoded to memeory for the best performance

### ISSUE THREAD

**Issue by bbauerma** [TUW-GEO/yeoda#3]
sgrt/common/utils/ts_slice_shape_2ram.py needs improvement. In addition to available memory size, the maximum limit of loading array size is also important to have the best performance.

**Comment by cnavacch** [comment]
This feature was implemented in `tempinator`, but could be open-sourced to `veranda`. See the following issue: https://github.com/TUW-GEO/veranda/issues/14
