### ISSUE TITLE
tiled .nc files not readable

### ISSUE THREAD

**Issue by bbauerma** [TUW-GEO/yeoda#9]
something is not working:
https://github.com/TUW-GEO/yeoda/blob/8994df969fb70ed6746c35523abacfc61818c9d9/src/yeoda/products/scatsar_swi.py#L143

**Comment by sebhahn** [comment]
What was the problem? Is there something to document?

**Comment by claxn** [comment]
To close this issue: A decoding function was wrongly applied to xarray datasets, which is now fixed in the previous commit 906da11c9f7fbc3bf33c4059d8937510b92ced34.

**Comment by sebhahn** [comment]
Thanks! You can also mention the issue in a commit message and it will be references/closed automatically. 

e.g. "This commit fixes #9"

**Comment by claxn** [comment]
I know, but I forgot to mention it... anyway, thanks for the note.
